// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: message.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ONU_ConsultarNombres_FullMethodName = "/grpc.ONU/ConsultarNombres"
)

// ONUClient is the client API for ONU service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ONUClient interface {
	ConsultarNombres(ctx context.Context, in *Consulta, opts ...grpc.CallOption) (*RespuestaNombres, error)
}

type oNUClient struct {
	cc grpc.ClientConnInterface
}

func NewONUClient(cc grpc.ClientConnInterface) ONUClient {
	return &oNUClient{cc}
}

func (c *oNUClient) ConsultarNombres(ctx context.Context, in *Consulta, opts ...grpc.CallOption) (*RespuestaNombres, error) {
	out := new(RespuestaNombres)
	err := c.cc.Invoke(ctx, ONU_ConsultarNombres_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ONUServer is the server API for ONU service.
// All implementations must embed UnimplementedONUServer
// for forward compatibility
type ONUServer interface {
	ConsultarNombres(context.Context, *Consulta) (*RespuestaNombres, error)
	mustEmbedUnimplementedONUServer()
}

// UnimplementedONUServer must be embedded to have forward compatible implementations.
type UnimplementedONUServer struct {
}

func (UnimplementedONUServer) ConsultarNombres(context.Context, *Consulta) (*RespuestaNombres, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConsultarNombres not implemented")
}
func (UnimplementedONUServer) mustEmbedUnimplementedONUServer() {}

// UnsafeONUServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ONUServer will
// result in compilation errors.
type UnsafeONUServer interface {
	mustEmbedUnimplementedONUServer()
}

func RegisterONUServer(s grpc.ServiceRegistrar, srv ONUServer) {
	s.RegisterService(&ONU_ServiceDesc, srv)
}

func _ONU_ConsultarNombres_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Consulta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ONUServer).ConsultarNombres(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ONU_ConsultarNombres_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ONUServer).ConsultarNombres(ctx, req.(*Consulta))
	}
	return interceptor(ctx, in, info, handler)
}

// ONU_ServiceDesc is the grpc.ServiceDesc for ONU service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ONU_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.ONU",
	HandlerType: (*ONUServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConsultarNombres",
			Handler:    _ONU_ConsultarNombres_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
